dist: bionic
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: mM+P7j+BzQLWidBUIJoXMjRc7OgRdwYLZo5qpX/wkS1dQNPZ6kXi9nqIDky+5a8c8iAbaE6MOd7PDmeicglQoMNwoDrdt43Gl3uVGU9Yj+c6RK7lSiAnpJrfZhlDs9ctois+V7Qny20armjEGkOQKCHnctldHpFJ06KGItRyPcoYLXlPLQCyGwkfveFomf7neqVobLoRbXxIaCNFZPxcbTFe9IAKetPBf884HSIjGTHT0J2oMFbuKPJKKBjTTLyQ/A+w0tc8DP9Nl7fsHxF7Q4ofyFWxCJrV89JJag9iy4SIprU9F7RuS+4mU6jlr5M/C7tDFLi9qqy0pukBtmzAg/9vX8J08bbW0JXQIMZsbtfLU3DaA2G1Sqts+TENFVzhTn2qa4xACxhAnwwwpiLAD/aWiYHzIs6IvhIP/VzfINVrltXz3pRWG1mdON0tgieUIQ8EXPTJBWNy0olgXhq96z1Xcf4iAZN7U4dblAWNj51v9SIzCaevNW1GTlHblP1zPSKw1JVadvlU+22It9JIgadD/zZgoGKx/CTMsSPuEjhhPT0kCSf/ufNUFeT9BgUPDROPc18kQkFHRipFwyYri67vZUF1ulQkYCe7maov+qQl1bPUK/wFWIKTW3PM8Rqqj+bVZUpifpsCPtlerFCqinf7ehQhH5qyGycg6ihGsTw=
  on:
    repo: CatInCosmicSpace/travis-tag-test
